### ISSUE TITLE
sample rate of this module

### ISSUE THREAD

**Issue by desword** [dixel/wifi-linux#2]
Hi, It is a fantastic work that is what I want now. However, I want to know that what 's the exact sampling rate of rssi?

**Comment by dixel** [comment]
Hi! Thanks for the feedback!
For now it's NetworkManager's sampling rate, the tool adds a new point each time it thinks the signal strength changed.
I don't really like this behavior and in the previous version I had 0.5/1.0 Hz sampling frequency but removed to only collect the data when it changes (which in my case was once per 3-4 seconds, but it can be software/hardware specific).
So answering your question, the exact sampling could be found in NetworkManager+dbus documentation.
To make tool more precise in terms of timing we can bring back X-axis as time and not as a function of a signal change.

**Comment by desword** [comment]
thanks for your response,  I will try to do some further coding to improve the sampling rate. Maybe to achieve about xkHz levels. I am not sure whether it is possible for the COTS wireless nic, e.g. intel 5300 nic, to achieve this high sampling rate.
Or could yo. please provide some advice for m,  thanks very much.
