### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe5 in position 0: unexpected end of data

### ISSUE THREAD

**Issue by ev01ing** [dixel/wifi-linux#3]
```
Traceback (most recent call last):
  File "list_rssi.py", line 120, in <module>
    wfl.form_rssi_dic()
  File "list_rssi.py", line 59, in form_rssi_dic
    print "".join(["%s" % k for k in ssid])
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe5 in position 0: unexpected end of data
```

if the wifi name has unicode character, may happen.

```
            try:
                self.rssid[u"".join([u"%s" % k for k in ssid])] = int(strength)
            except UnicodeDecodeError:
                pass
```
this can avoid, but the WIFI's RSSI will not get.

**Comment by dixel** [comment]
Reproduced, good old python error :)
I am on it.

**Comment by dixel** [comment]
Fixed that but only by using python3 ([here](https://github.com/dixel/wifi-linux/tree/python3)).
Will also check if I can keep backward-compatibility and then merge into master.
Please check if that fixes the issue for you.

**Comment by dixel** [comment]
now should work in both python 2 and 3 #4
