### ISSUE TITLE
cannot run on raspberry pi

### ISSUE THREAD

**Issue by ev01ing** [dixel/wifi-linux#5]
Linux version 4.9.59-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611) ) #1047 SMP Sun Oct 29 12:19:23 GMT 2017

Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l

this is my system info.

maybe you don't know the reason and cannot resolve it. and is does not matter. 

thx

**Comment by dixel** [comment]
Unfortunately it didn't work on rapsbian for me as well, because rpi doesn't use NetworkManager:
#1
